### ISSUE TITLE
Change status message color to green when deployed

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#108]
On the Organizations page, when a cluster is deployed, I suggest changing the color of the status message to green.  It is currently displayed in red both when deployed and when not deployed.

![image](https://user-images.githubusercontent.com/54070345/206471438-648b8881-9d82-44b8-bbe7-4d984175cfa8.png)

**Comment by cugarteblair** [comment]
fixed 1.7.4
