### ISSUE TITLE
Touch up how min nodes are handled

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#113]
Currently, when a user deploys a cluster there is a fake entry added to the expiration table for 1 year.  This then shows up in the result list on the manage cluster page.

If we use a fake entry, I suggest increasing the time of the expiration to be something like 10 years or longer.  Also, is there a way to change what is displayed on the result table on the manage cluster page to indicate to the user that this is the min-node kicking in and this is a system initiated command.

Conversely, maybe there is a way to implement this without using a fake entry and then system uses the owner to issue a command that doesn't expire.

**Comment by cugarteblair** [comment]
Better presentation layer code was added so that the user only sees that there is "No Expiration" in v2.1.3
