### ISSUE TITLE
Option to force update a cluster

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#136]
The web update button should have the option to take effect immediately, and clear the queue just like the destroy - e.g. I wanted to reduce the number of nodes in a cluster to 1, but I couldn't because there were existing requests (in this case the initial deploy with a TTL of 60 minutes).

This may also need to be tied to a view of the upcoming changes that are still pending.

**Comment by cugarteblair** [comment]
fixed in v1.8.5
