### ISSUE TITLE
Weird formatting in pending capacity list

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#145]
After making a few API calls to increase (and also keep the number of nodes the same), the pending capacity list was weirdly formatted.

![image](https://user-images.githubusercontent.com/54070345/212428205-5ccd2f94-e52d-4dc1-a98f-99512a2a56c2.png)

**Comment by cugarteblair** [comment]
This was fixed in v2.02
