### ISSUE TITLE
Provide "public" variable to terraform

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#176]
Currently, the load balancer for each cluster uses the name of the cluster to determine whether or not it should be public.  This poses a challenge because if we want to have multiple public clusters, they can't all have the same name.  And if we use the testsliderule.org domain, we have some concerns that overlapping names may cause unintended issues.

Having a dedicated variable called "public" would resolve this issue.  Ideally, this option would be provided in the deploy page as a checkbox (defaulted to off).  The "public" variable would have the value of "true" if selected, and "false" if not selected.

**Comment by cugarteblair** [comment]
This was added to v2.1.8
