### ISSUE TITLE
API initiated num_node request to public sliderule cluster made it private

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#204]
From a Python script I made a num_nodes request to increase the number of nodes in the public sliderule cluster from 7 nodes to 30 nodes.  When I did that, the nodes went to 30, but the cluster was no longer reachable because it had been changed to a private cluster.  Subsequent attempts to use the Update command from the web to make the cluster public did not work.

**Comment by jpswinski** [comment]
It also looks like a scale in event initiated from an expiration of a pending capacity, also takes it to a private cluster.

**Comment by cugarteblair** [comment]
This was fixed in v3.2.0
