### ISSUE TITLE
Changing admin max node cap oddities

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#207]
When I tried to change the admin max node cap for the ESR organization using the admin page, it first gave me an error saying that I needed to fill out the tokens field.  I looked at the developers org and saw that tokens = `{"": ""}` and so I populated the same in the ESR organization and it worked.

But then when I went to the ESR manage cluster page, it showed the Max node cap at the same value I set the admin max node cap.  I went back to the admin page and verified that the max node cap was set correctly and unchanged, and then I went back to the manage cluster page and verified that the max node cap was still reflecting the admin max node cap and not the actual max node cap.

**Comment by jpswinski** [comment]
Also, the actual max node cap is still the value shown on the admin page and not the value shown on the manage cluster page.  So to work around it currently, we need to do an update on the manage cluster page to get the value we want to stick.

**Comment by cugarteblair** [comment]
This was fixed in v3.2.0
