### ISSUE TITLE
Display only local timezone times

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#85]
When a time is displayed by the ps website, it should be in the local timezone of the client viewing the page.

For instance, here the UTC time is being displayed:
![image](https://user-images.githubusercontent.com/54070345/203421672-7daf043c-a190-4f6a-b449-e4e9c09fe427.png)

**Comment by cugarteblair** [comment]
This was fixed in v3.2.0
