### ISSUE TITLE
Provide year-to-date cost metric for a cluster

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#86]
On the cluster management page or the summary box, the year-to-date cost incurred by the organization should be displayed.

This should nominally start from October 1st (but maybe an option is needed to set it to an arbitrary starting date if other institutions have different fiscal year boundaries).

Also - at some point I imagine it being October 2nd, and someone asking "what was the total year cost of last fiscal year".  I know that is a harder problem because it requires saving the information.  But at some point we should probably support that as well.

**Comment by cugarteblair** [comment]
This was added in v2.0.4
