### ISSUE TITLE
Readme documentation updates

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-ps-web#9]
The following updates to the readme are needed:
  - typo in the DB restoration command
  - instructions to install the docker compose cli plugin
  - env files needed before building the docker web container
  - need to make the ~/logs directory
  - need to make the ./credentials directory in both server and web
  - need crt files for both server and web
  - move the instructions for restoring the db above where it currently is

**Comment by cugarteblair** [comment]
These were done or are OBE
